### ISSUE TITLE
I have a browser grabber problem

### ISSUE THREAD

**Issue by seoton08499** [NightfallGT/Mercurial-Grabber#4]
아이디만 발견이 되고 비밀번호는 없습니다

**Comment by NightfallGT** [comment]
It will return an empty text file if there are no saved passwords in Chrome

**Comment by SauhardGaming** [comment]
Same here

**Comment by NightfallGT** [comment]
It will send an empty text file if there arent any saved passwords in the browser

**Comment by SauhardGaming** [comment]
> send an empty text file if there arent any saved passwords in the browser

I used the logger for myself and it just send my windows info, product key, minecraft session, and many useless embeds in the image below 
![image](https://user-images.githubusercontent.com/56781809/120273623-634c6500-c2cc-11eb-906a-6fc4dc7072e0.png)
