### ISSUE TITLE
Funniest shit ever what even is this shit, took me 5 seconds to reverse and find the webhook

### ISSUE THREAD

**Issue by 0000000O0Oo** [NightfallGT/Mercurial-Grabber#45]
Well some 10 year old kids on discord is having fun making servers and trying to infect people this is pretty lame

Anyway i would suggest to spam webhooks if you find someone trying to infect people with it even though they will eventually make another webhook to receive data

`while true do; proxychains curl <webhook> -XPOST -d "content=YOURGAY&username=YOURGAY&avatar=YOURGAY"; done`

also you can report it directly to discord...

**Comment by AstroOnYT** [comment]
the grabber builder itself isnt skidded
