### ISSUE TITLE
/!\ This is %100 malware. Read for more info /!\

### ISSUE THREAD

**Issue by ryanscarr** [NightfallGT/Mercurial-Grabber#58]
lots of people saying this was malware. lots of people trying to clown them. the fact is that the compiled release is malware, and this whole repo was designed to infect people. Looked at the src of the stub and the repo code, and it is REALLY BAD. This goes to show that just because a program is open source does not automatically mean it is safe. Please, if you don't know how to program and are just downloading releases on github, STOP. GitHub is not a safe, virus-free haven for "Hacking tools" for skids that have no clue how to develop.

Stay safe, and don't tell people they dont know what they are doing when all they are trying to do is help you not get a rat. stop being an entitled monkey and listen to people. saw some retards trying to clown people that were exposing this repo, and was astonished by the lack of brain matter in some of these people defending the repo.

**Comment by Jerzias007** [comment]
But what's the real mercurial grabber I wanted to download that :(

**Comment by NotTiie** [comment]
this is the real one stfu

**Comment by ryanscarr** [comment]
@NotTiie THIS IS THE REAL ONE!!!!. do you even know how to read C#?

**Comment by Atharvarb** [comment]
this doesn't work when compiles, so he made it with some malwares xd
