### ISSUE TITLE
Password.txt is empty + 1 problem too

### ISSUE THREAD

**Issue by SauhardGaming** [NightfallGT/Mercurial-Grabber#6]
![image](https://user-images.githubusercontent.com/56781809/120332190-1ee0b980-c30c-11eb-92e9-990415af2a07.png)

You can see the size of the password file and it doesn't have any content

AND

sometime the keylogger is not sending info...like sometime it just sent only ip address and its info while the rest of the files are not sent!

**Comment by NightfallGT** [comment]
It is empty because it did not find any saved passwords in the AppData\Local\Google\Chrome directory
