### ISSUE TITLE
DONT USE Mercurial

### ISSUE THREAD

**Issue by ghost** [NightfallGT/Mercurial-Grabber#70]
Mercurial grabs your data from your browsers such as cookies, passwords and data
Don't use it.

Make your own grabber and compile. Here's proof the dev is skidded it

https://i.imgur.com/lZ2MngZ.png

**Comment by makarothacks** [comment]
bro how can i save myself if i already opened

**Comment by ghost** [comment]
lmao u cant

**Comment by AstroOnYT** [comment]
nah thats cap the proof you showed indicated no webhook, until u show an instance of a webhook this is proved false. another thing this has been open source for a long time you think it wouldnt be found that this is a fake in the beginning

**Comment by ghost** [comment]
he's hiding his personal webhook in base64 dumbass and he made this for "educational purposes" this shit is bad bc its also dh LMAO

**Comment by AstroOnYT** [comment]
i dont see it

**Comment by ghost** [comment]
nope. this is still not true

**Comment by NeonWaree** [comment]
Use Hazard Grabber, It's not dual hooked and its Open Source
